# Site settings
title: <Seu Nome>
email: <Seu Nome>@inf.ufg.br
description: <Seu Curso>
baseurl: "/" 
url: "" 
twitter_username:
github_username:
lattes_id:
nome_citacoes: 
linkedin_username:
stackoverflow_username: 
stackoverflow_id: 

exclude:
  - 'vendor'
  - 'Gemfile*'
  - 'README.md'
  - '*.yml'
  - 'LICENSE'

# Build settings
markdown: kramdown